name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: Unetic/packages/.github/workflows/reusable-web.yml@main
    with:
      release: false
