name: Deploy development build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: Unetic/.github/.github/workflows/openwrt-package.yml@main
    with:
      package-name: unetic-web
      build-kind: web
      deploy: true
    secrets: inherit
