name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    uses: Unetic/.github/.github/workflows/release.yml@afe9daad37b076fdcad596659682b00cc3c5248d
    with:
      build-kind: web
    permissions:
      contents: write
