name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    uses: Unetic/.github/.github/workflows/release.yml@main
    with:
      package-name: unetic-web
      build-kind: web
    permissions:
      contents: write
